### PR TITLE
HALify only  when negotiating a HAL mediaType

### PR DESCRIPTION
**Pull request by antoine-richard**
_Hi. With this PR, I would like to discuss how to best handle the issue I have_

**halify only  when negotiating a HAL mediaType (but not another mediaType handled by the app)**

Here's my use-case:
[I have an app](https://github.com/boillodmanuel/rest-from-zero-to-hero) which handles `hal+json` and `json`. When returning json, the representation isn't wrapped with HAL. All is fine here.

My problem is that the app returns a hal+json representation by default (i.e with no accept header,which is equivalent to `accept: */*`). I'd have preferred json :/

Have I missed something?

If not, I tried to solve this issue with this PR in which:
* the end-user can provide a full list of the mediaTypes supported by his app.
* this list is given to Negotiator which finds the mediaType to use.
* No HALification occurs when it's not a "HAL mediaType"

Best,
Antoine

### CODE REVIEW

**Comment by bleupen** [comment]
Hello and thanks for the PR!

Would you mind working up a couple of unit tests to spell out the use cases you have in mind?

**Comment by antoine-richard** [comment]
Sure!
I'll get back to you as soon as possible.

**Comment by antoine-richard** [comment]
Hi,

I've pushed a test illustrating my use-case.
I took the opportunity to slightly rework the API. Hopefully it will be more understandable.

Please let me know what you think.

**Comment by bleupen** [comment]
Awesome, thank you!

**Comment by antoine-richard** [comment]
Hi,
How can I help you to get this merged?

**Comment by bleupen** [comment]
Hi Antoine,

Thanks for the nudge. My family and I moved houses over the holidays so my mind has been elsewhere.

I'll take a look at it this afternoon. Shouldn't take too long. 

Brad

**Comment by bleupen** [comment]
Ok just looked through the code. I simplified the configuration a little by adding a ```requireHalJsonAcceptHeader``` boolean configuration parameter, which triggers hal processing only if the client explicitly requests ```application/hal+json``` Sound good?

**Comment by antoine-richard** [comment]
Hi Brad,

Sorry, didn't want to bother you during holidays.

This simplification can be sufficient. I just want to make sure the following cases are supported:
Let's say the client request no particular content-type (i.e. `*/*`) and:
    1. the server is configured to return application/hal+json by default? (not implemented in the tests I pushed)
    2. the server is configured to return another media-type (application/json for example) by default? (tested)

Can I see your code somewhere?

**Comment by bleupen** [comment]
ok back from holidays. i pushed my code up to a "conneg" branch

**Comment by antoine-richard** [comment]
Hi,

Tested the conneg branch, thank you.
It works for me :+1:

**Pull request closed without merging**
