### PR TITLE
Hapi v17 Support

### PR DESCRIPTION
**Pull request by alexb-uk**
Ref: Issue Hapi v17 Support #103 

Changes include:

- Updates to support api breaking changes moving from HAPI v16 to v17
- Switch from jshint to eslint + prettier
  - eslint has much better auto-fixing to improve code readability.
- Refactored to include async / await to aid readability
- Updated all 3rd party libs to current versions
- Fixed number of typos causing compiler errors in examples

### CODE REVIEW

**Comment by alexb-uk** [comment]
Actually above should read "Started refactoring to use async / await to aid readability" there is still a lot of "then's" to be updated.

**Comment by alexb-uk** [comment]
It seems like the project has been quiet for a while now.

Could a maintainer confirm if they still have time to work on this project? If not I'll look into publishing my fork on NPM and will try to keep it up to date. This library has been really useful for me so would be a shame for it to drift away.

Thanks

**Comment by bleupen** [comment]
Hi Alex, I apologize. 

Day job and life have kept me pretty busy. We still have not upgraded to hapi 17 at my company because of the massive rewrite it requires. 

Thank you so much for the effort you have put into this library. I am definitely interested in moving it forward. I will set aside some time this week to get rolling on v17 support as well as some other ideas I have. 

Thanks again,
Brad

**Comment by dumbbaldmonkey** [comment]
Any status change on getting support for v17 merged in?

**Comment by alexb-uk** [comment]
Closing as Hapi is now on version 19 and also this PR now have merge conflicts.

**Pull request closed without merging**
